name : Firebase Deploy

on: 
  push:
      branches:
            -master

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
            node-version:'14'
      - run : cp firebase.json
      - run : cp .firebaserc
      - run : yarn 
      - run : yarn build
        uses : w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  